# Generated by Django 3.2.7 on 2021-09-18 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdata',
            options={'verbose_name': 'User Data'},
        ),
    ]
