# Generated by Django 3.2.7 on 2021-09-19 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_userdata_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='liters_drunk',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='minutes_walked',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='eye_breaks',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='total_break_time',
            field=models.IntegerField(null=True),
        ),
    ]
